# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Blog
    url: /#blog
    weight: 10
  - name: About
    url: /#about
    weight: 20
